# ============================================================================
# SSM Parameter Store - Application Secrets
# ============================================================================
# Secrets are auto-generated by Terraform on first apply using random_password.
# After creation, manage values directly in SSM — Terraform ignores changes.
# Naming convention: /{environment}/{project}/{secret_name}
# ============================================================================

resource "random_password" "secret_key" {
  length  = 64
  special = true

  lifecycle {
    ignore_changes = [length, special]
  }
}

resource "random_password" "first_superuser_password" {
  length           = 32
  special          = true
  override_special = "!_-"

  lifecycle {
    ignore_changes = [length, special, override_special]
  }
}

module "ssm_secret_key" {
  source = "../modules/aws_ssm_parameter"

  context = local.context
  name    = "secret_key"
  value   = random_password.secret_key.result
}

module "ssm_first_superuser_password" {
  source = "../modules/aws_ssm_parameter"

  context = local.context
  name    = "first_superuser_password"
  value   = random_password.first_superuser_password.result
}

module "ssm_smtp_password" {
  source = "../modules/aws_ssm_parameter"

  context = local.context
  name    = "smtp_password"
  value   = "placeholder"
}
