# ============================================================================
# SSM Parameter Store - Application Secrets
# ============================================================================
# Secrets are auto-generated by Terraform on first apply using random_password.
# After creation, manage values directly in SSM — Terraform ignores changes.
# Naming convention: /{environment}/{project}/{secret_name}
# ============================================================================

resource "random_password" "secret_key" {
  length  = 64
  special = true

  lifecycle {
    ignore_changes = [length, special]
  }
}

resource "random_password" "first_superuser_password" {
  length           = 32
  special          = true
  override_special = "!@#$%^&*"

  lifecycle {
    ignore_changes = [length, special, override_special]
  }
}

resource "aws_ssm_parameter" "secret_key" {
  name  = "/${var.environment}/${var.project}/secret_key"
  type  = "SecureString"
  value = random_password.secret_key.result

  tags = local.context.common_tags

  lifecycle {
    ignore_changes = [value]
  }
}

resource "aws_ssm_parameter" "first_superuser_password" {
  name  = "/${var.environment}/${var.project}/first_superuser_password"
  type  = "SecureString"
  value = random_password.first_superuser_password.result

  tags = local.context.common_tags

  lifecycle {
    ignore_changes = [value]
  }
}

resource "aws_ssm_parameter" "smtp_password" {
  name  = "/${var.environment}/${var.project}/smtp_password"
  type  = "SecureString"
  value = "placeholder"

  tags = local.context.common_tags

  lifecycle {
    ignore_changes = [value]
  }
}
